### ISSUE TITLE
JCronofy doesn't support all possible values for a scope

### ISSUE THREAD

**Issue by skiffer** [Biacode/jcronofy#2]
JCronofy client fails when I try to revoke or get an access token by a code.

Need to expand the supportable types of a scope:
create_calendar 
event_reminders
read_free_busy
change_participation_status

Like a workaround, I reconfigure a client for ignoring this one.
    `private CronofyClientImpl createCronofyClient() {
        return new CronofyClientImpl(
                ClientBuilder.newClient(
                        new ClientConfig(
                                new JacksonJsonProvider()
.configure(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL, true)
                        )
                )
        );
    }`

**Comment by Biacode** [comment]
Will be added in next release.
