### ISSUE TITLE
Use of European datacenter 

### ISSUE THREAD

**Issue by ChrisPeel-Qudini** [Biacode/jcronofy#44]
Can we expand the CronofyClientImpl class to be able to use a different Cronofy target endpoint?  Our company has registered with api-de.cronofy.com so we would like to be able to choose this option when instantiating the CronofyClient.

**Comment by ChrisPeel-Qudini** [comment]
@Biacode I have created a local branch with this change however I would need to be added to the repo to raise the pull request.  Thanks.

**Comment by Biacode** [comment]
Hi @ChrisPeel-Qudini,
No problem. Let me know when you are done.

**Comment by Biacode** [comment]
Hi @ChrisPeel-Qudini 
Thanks for your contribution.
The #46 PR is merged. I am planning to make some changes there.
After the snapshot version will be published.
Please let me know if anything works fine so I can publish a new release version.

**Comment by Biacode** [comment]
@ChrisPeel-Qudini `1.2.0-SNAPSHOT` has been deployed. Please have a look.

**Comment by Biacode** [comment]
@ChrisPeel-Qudini 1.2.0 version has been released

**Comment by ChrisPeel-Qudini** [comment]
Hi @Biacode I ran the updated app with 1.2 and it's working as expected with the additional constructor.
